FROM python:3.12.6-slim

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

WORKDIR /backend

RUN pip install --no-cache-dir poetry

COPY pyproject.toml poetry.lock ./

RUN poetry config virtualenvs.create false

RUN poetry install

COPY . /backend

#TODO: gunicorn launch app
CMD ["bash", "-c", "alembic upgrade head && uvicorn app.main:fastapi_app --host 0.0.0.0 --port ${APP_PORT} --reload"]
