"""payments, users, products

Revision ID: b14d202b42dd
Revises:
Create Date: 2024-11-02 20:02:57.668411

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b14d202b42dd"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "products",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("source_product_url", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("preview_urls", sa.JSON(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint(
            "name",
            "source_product_url",
            name="unique_name_source_product_url_constraint",
        ),
        sa.UniqueConstraint("source_product_url"),
    )
    op.create_index(op.f("ix_products_id"), "products", ["id"], unique=False)
    op.create_table(
        "users",
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("is_superuser", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_table(
        "payments",
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("customer_email", sa.String(), nullable=False),
        sa.Column("invoice", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("failureReason", sa.String(), nullable=True),
        sa.Column("errorCode", sa.Integer(), nullable=True),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("ccy", sa.Integer(), nullable=False),
        sa.Column("finalAmount", sa.Integer(), nullable=True),
        sa.Column("createdDate", sa.DateTime(timezone=True), nullable=False),
        sa.Column("modifiedDate", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reference", sa.String(), nullable=True),
        sa.Column("destination", sa.String(), nullable=True),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_payments_id"), "payments", ["id"], unique=False)
    op.create_index(op.f("ix_payments_invoice"), "payments", ["invoice"], unique=True)
    op.create_index(
        op.f("ix_payments_product_id"), "payments", ["product_id"], unique=False
    )
    op.create_table(
        "cancel_lists",
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=True),
        sa.Column("ccy", sa.Integer(), nullable=True),
        sa.Column("createdDate", sa.DateTime(timezone=True), nullable=True),
        sa.Column("modifiedDate", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approvalCode", sa.String(), nullable=True),
        sa.Column("rrn", sa.String(), nullable=True),
        sa.Column("extRef", sa.String(), nullable=True),
        sa.Column("payment_id", sa.UUID(), nullable=False),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["payment_id"],
            ["payments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("payment_id"),
    )
    op.create_index(op.f("ix_cancel_lists_id"), "cancel_lists", ["id"], unique=False)
    op.create_table(
        "payments_info",
        sa.Column("maskedPan", sa.String(), nullable=False),
        sa.Column("approvalCode", sa.String(), nullable=True),
        sa.Column("rrn", sa.String(), nullable=True),
        sa.Column("trainId", sa.String(), nullable=True),
        sa.Column("terminal", sa.String(), nullable=False),
        sa.Column("bank", sa.String(), nullable=True),
        sa.Column("paymentSystem", sa.String(), nullable=False),
        sa.Column("paymentMethod", sa.String(), nullable=False),
        sa.Column("fee", sa.Integer(), nullable=True),
        sa.Column("country", sa.String(), nullable=True),
        sa.Column("agentFee", sa.Integer(), nullable=True),
        sa.Column("payment_id", sa.UUID(), nullable=False),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["payment_id"],
            ["payments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("payment_id"),
    )
    op.create_index(op.f("ix_payments_info_id"), "payments_info", ["id"], unique=False)
    op.create_table(
        "tips_info",
        sa.Column("employeeId", sa.String(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=True),
        sa.Column("payment_id", sa.UUID(), nullable=False),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["payment_id"],
            ["payments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("payment_id"),
    )
    op.create_index(op.f("ix_tips_info_id"), "tips_info", ["id"], unique=False)
    op.create_table(
        "wallets_data",
        sa.Column("cardToken", sa.String(), nullable=False),
        sa.Column("walletId", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("payment_id", sa.UUID(), nullable=False),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["payment_id"],
            ["payments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("payment_id"),
    )
    op.create_index(op.f("ix_wallets_data_id"), "wallets_data", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_wallets_data_id"), table_name="wallets_data")
    op.drop_table("wallets_data")
    op.drop_index(op.f("ix_tips_info_id"), table_name="tips_info")
    op.drop_table("tips_info")
    op.drop_index(op.f("ix_payments_info_id"), table_name="payments_info")
    op.drop_table("payments_info")
    op.drop_index(op.f("ix_cancel_lists_id"), table_name="cancel_lists")
    op.drop_table("cancel_lists")
    op.drop_index(op.f("ix_payments_product_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_invoice"), table_name="payments")
    op.drop_index(op.f("ix_payments_id"), table_name="payments")
    op.drop_table("payments")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_products_id"), table_name="products")
    op.drop_table("products")
    # ### end Alembic commands ###
