from typing import Union, Dict

from pydantic import BaseModel


class ErrorModel(BaseModel):
    detail: Union[str, Dict[str, str]]


class AuthError:
    FORBIDDEN = "FORBIDDEN"
    NOT_VERIFY_EMAIl = "NOT_VERIFY_EMAIl"
    UNAUTHORIZED = "UNAUTHORIZED"
    RESET_PASSWORD_BAD_TOKEN = "RESET_PASSWORD_BAD_TOKEN"
    RESET_PASSWORD_INVALID_PASSWORD = "RESET_PASSWORD_INVALID_PASSWORD"
    LOGIN_BAD_CREDENTIALS = "LOGIN_BAD_CREDENTIALS"


class UserError:
    USER_NOT_FOUND = "USER_NOT_FOUND"
    UPDATE_USER_EMAIL_ALREADY_EXISTS = "UPDATE_USER_EMAIL_ALREADY_EXISTS"
    REGISTER_USER_ALREADY_EXISTS = "REGISTER_USER_ALREADY_EXISTS_RESPONSE"
    UPDATE_USER_INVALID_PASSWORD = "UPDATE_USER_INVALID_PASSWORD"
    USER_WITH_THIS_EMAIL_ALREADY_EXISTS = "USER_WITH_THIS_EMAIL_ALREADY_EXISTS"


class ProductError:
    PRODUCT_NOT_FOUND = "PRODUCT_NOT_FOUND"
    PRODUCT_WITH_THIS_NAME_ALREADY_EXISTS = "PRODUCT_WITH_THIS_NAME_ALREADY_EXISTS"
    PRODUCT_WITH_THIS_SOURCE_PRODUCT_URL_ALREADY_EXISTS = "PRODUCT_WITH_THIS_SOURCE_PRODUCT_URL_ALREADY_EXISTS"


class ErrorCode(AuthError, UserError, ProductError):
    pass
