class ProductError:
    NOT_FOUND = "PRODUCT_NOT_FOUND"
    NAME_ALREADY_EXISTS = "PRODUCT_WITH_THIS_NAME_ALREADY_EXISTS"
    SOURCE_URL_ALREADY_EXISTS = "PRODUCT_WITH_THIS_SOURCE_PRODUCT_URL_ALREADY_EXISTS"
